### ISSUE TITLE
Create numpy verions of sorting algorithms

### ISSUE THREAD

**Issue by ianmkenney** [GrantDenbrock/Library#4]
Translate all of the algorithms into numpy. New file should be called `Sorting_numpy.py`.

**Comment by GrantDenbrock** [comment]
I've been looking on google this afternoon but I think I need to know what we hope to accomplish by doing this. Am I just turning array[x] into np.array[x] to enhance speed? @ianmkenney

**Comment by ianmkenney** [comment]
bump @GrantDenbrock
